### ISSUE TITLE
2023 Q1-Q2 TODO (v0.3.3)

### ISSUE THREAD

**Issue by Ar-Ray-code** [Ar-Ray-code/YOLOX-ROS#32]
- [ ] Add CI (OpenVINO, TensorRT, TFLite for C++)
- [ ] Create base launch.py file and include it
- [ ] [PINTO_model_zoo](https://github.com/PINTO0309/PINTO_model_zoo) full support
